ENV DEBIAN_FRONTEND=noninteractive

COPY build/common.sh /build/common.sh

# 3. System Update
COPY build/system_update /build/system_update
RUN /build/system_update/run.sh

# 5. Install tools
COPY build/build_tools /build/build_tools
RUN /build/build_tools/run.sh

# 13. Astrometry
COPY build/astrometry /build/astrometry
RUN /build/astrometry/run.sh

# 11. Hostname
COPY build/hostname /build/hostname
RUN /build/hostname/run.sh

# 12. Skychart
COPY build/skychart /build/skychart
RUN /build/skychart/run.sh

# 16. Pentax
COPY build/pentax /build/pentax
RUN /build/pentax/run.sh

# 2. Login as root
COPY build/sudo /build/sudo
RUN /build/sudo/run.sh

# 15. gphoto2
COPY build/gphoto2 /build/gphoto2
RUN /build/gphoto2/run.sh

# 7. Webserver
COPY www /home/pi/www
COPY build/webserver /build/webserver
RUN /build/webserver/run.sh

# 14. Dslrdashboard
COPY build/dslrdashboard /build/dslrdashboard
RUN /build/dslrdashboard/run.sh

# 18. Lin_guider
COPY build/lin_guider /build/lin_guider
RUN /build/lin_guider/run.sh

# 19. OpenSkyImager
COPY build/openskyimager /build/openskyimager
RUN /build/openskyimager/run.sh

# 9. TCP to Serial
COPY build/ser2net /build/ser2net
RUN /build/ser2net/run.sh

# 20. QSI
COPY build/qsi /build/qsi
RUN /build/qsi/run.sh

# 24. INDI
COPY build/indi /build/indi
RUN /build/indi/run.sh

# 21. GoQat
COPY build/goqat /build/goqat
RUN /build/goqat/run.sh

# Provide access to RPi hardware interface utilities
COPY build/userland /build/userland
RUN /build/userland/run.sh

# 6. CPU and temp
COPY build/cpu_and_temp /build/cpu_and_temp
RUN /build/cpu_and_temp/run.sh

# 22. TTS
COPY build/audio /build/audio
RUN /build/audio/run.sh

# 23. nano /etc/rc.local
COPY build/run_control /build/run_control
RUN /build/run_control/run.sh

# 17. FTDI modules
COPY build/ftdi /build/ftdi
RUN /build/ftdi/run.sh

# Cleanup
RUN rm -rf /home/pi/www/images/*

# netstat is needed to launch noVNC (called within web server)
RUN apt-get -y install net-tools vim

# Create a startup script to run all our services
RUN echo "#!/usr/bin/env sh" > /start.sh && \
  echo "/etc/rc.local" >> /start.sh && \
  echo "service php5-fpm start" >> /start.sh && \
  echo "service nginx start" >> /start.sh && \
  echo "tail -f /dev/null" >> /start.sh && \
  chmod +x /start.sh

# Nginx web server
EXPOSE 80

# NoVNC
EXPOSE 5551 5552 5553

# INDI Web Sockets
EXPOSE 7624
# INDI Web Manager
EXPOSE 8624

# INDI Control Panel
EXPOSE 8888

# VNC
EXPOSE 5900 5901

CMD ["/start.sh"]