ENV DEBIAN_FRONTEND=noninteractive

# 3. System Update
RUN apt-get -y update
RUN apt-get -y upgrade

# 5. Install tools
RUN apt-get -y install \
  aptitude \
  bc \
  build-essential \
  g++ \
  gcc \
  make \
  nano \
  usbutils \
  wget

# 10. Pushover Notification
RUN apt-get -y install \
  curl \
  libwww-perl

# 11. Hostname
RUN echo "iAstroHub" > /etc/hostname
# 127.0.1.1 was used in the initial README; I believe it should be 127.0.0.1.
RUN echo "127.0.0.1 iAstroHub" >> /etc/hosts

# 12. Skychart
RUN apt-get -y install \
  espeak \
  libglu1-mesa \
  libgtk2.0-0 \
  libpango1.0-0 \
  xplanet
RUN mkdir /skychart
WORKDIR /skychart
# Install on Raspbian/arm
RUN uname -a | grep arm && wget http://sourceforge.net/projects/libpasastro/files/version%201.1/libpasastro_1.1-15_armhf.deb || true
RUN uname -a | grep arm && dpkg -i libpasastro_1.1-15_armhf.deb || true
RUN uname -a | grep arm && wget http://sourceforge.net/projects/skychart/files/1-software/version_4.0/skychart_4.0-3575b_armhf.deb || true
RUN uname -a | grep arm && dpkg -i skychart_4.0-3575b_armhf.deb || true
# Install on Debian/x64
RUN uname -a | grep x86_64 && wget http://sourceforge.net/projects/libpasastro/files/version%201.1/libpasastro_1.1-14_amd64.deb || true
RUN uname -a | grep x86_64 && dpkg -i libpasastro_1.1-14_amd64.deb || true
RUN uname -a | grep x86_64 && wget http://sourceforge.net/projects/skychart/files/1-software/version_4.0/skychart_4.0-3575b_amd64.deb || true
RUN uname -a | grep x86_64 && dpkg -i skychart_4.0-3575b_amd64.deb || true
# Correct dependencies after manual package installation.
RUN apt-get -fy install
# Install data set
RUN wget http://sourceforge.net/projects/skychart/files/2-catalogs/Nebulea/skychart-data-pictures_4.0-3421_all.deb
RUN dpkg -i skychart-data-pictures_4.0-3421_all.deb
WORKDIR /

# 16. Pentax
RUN apt-get -y install ufraw ufraw-batch libgtk2.0-dev
RUN wget https://github.com/asalamon74/pktriggercord/releases/download/v0.84.00/pkTriggerCord-0.84.00.src.tar.gz
RUN tar xvf pkTriggerCord-0.84.00.src.tar.gz
WORKDIR pktriggercord-0.84.00/
RUN make
RUN make install
WORKDIR /

# 2. Login as root
RUN apt-get -y install sudo
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)

# 7. Webserver
COPY www /home/pi/www
RUN chmod -R 777 /home/pi/www
RUN apt-get -y install \
  nginx \
  php5-cgi \
  php5-cli \
  php5-common \
  php5-fpm
COPY patches /patches
RUN LOCATION=/etc/php5/cgi/php.ini; patch -i /patches/$LOCATION.patch $LOCATION
RUN LOCATION=/etc/php5/cli/php.ini; patch -i /patches/$LOCATION.patch $LOCATION
RUN LOCATION=/etc/php5/fpm/php.ini; patch -i /patches/$LOCATION.patch $LOCATION
RUN LOCATION=/etc/nginx/sites-available/default; patch -i /patches/$LOCATION.patch $LOCATION

# 8. xvfb and vnc
RUN apt-get -y install \
  x11vnc \
  xfonts-75dpi \
  xfonts-cyrillic \
  xfonts-scalable \
  xvfb

