#!/bin/sh

if ! git diff-index --quiet HEAD --; then
  echo "Detected untracked changes to files checked into git."
  echo "You must commit or undo these changes prior to releasing."
  git status
  exit 1
fi

if ! uname -m | grep "arm" > /dev/null; then
  echo "You can only release when building on an ARM architecture."
  echo "Your architecture is: $(uname -m)."
  exit 2
fi

if ! docker info | grep Username > /dev/null; then
  docker login
fi

./make
VERSION=$(git rev-parse --short HEAD)
docker tag iastrohub astroswarm/iastrohub:$VERSION
docker tag iastrohub astroswarm/iastrohub:latest
docker push astroswarm/iastrohub:$VERSION
docker push astroswarm/iastrohub:latest
