ENV DEBIAN_FRONTEND=noninteractive

# 3. System Update
RUN apt-get -y update
RUN apt-get -y upgrade

# 5. Install tools
RUN apt-get -y install \
  aptitude \
  bc \
  build-essential \
  g++ \
  gcc \
  make \
  nano \
  usbutils \
  wget

# 10. Pushover Notification
RUN apt-get -y install \
  curl \
  libwww-perl

# 11. Hostname
RUN echo "iAstroHub" > /etc/hostname
# 127.0.1.1 was used in the initial README; I believe it should be 127.0.0.1.
RUN echo "127.0.0.1 iAstroHub" >> /etc/hosts
